# Generated by Django 6.0.3 on 2026-03-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike / Scooter'), ('ev', 'Electric Vehicle')], default='car', max_length=10),
        ),
    ]
