# Generated by Django 6.0.3 on 2026-05-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_booking_fine_amount_parkinglot_fine_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('overstay', 'Overstay — Fine Applied'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
