# Generated by Django 6.0.3 on 2026-04-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_unique_slot_number_per_lot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkingslot',
            options={'ordering': ['lot_id', 'slot_number']},
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='controller_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='last_sensor_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='occupancy_status',
            field=models.CharField(choices=[('empty', 'Empty'), ('occupied', 'Occupied'), ('unknown', 'Unknown')], default='empty', max_length=10),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='sensor_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('overstay', 'Overstay - Fine Applied'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
    ]
