# Generated by Django 6.0.3 on 2026-05-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_alter_parkingslot_options_parkingslot_controller_id_and_more'),
        ('parking', '0005_booking_qr_code'),
    ]

    operations = [
    ]
