# Generated by Django 6.0.3 on 2026-06-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_merge_20260526_1434'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parkingslot',
            name='unique_slot_number_per_lot',
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='hardware_slot_id',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='is_hardware_slot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('overstay', 'Overstay — Fine Applied'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='controller_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
