# Generated by Django 6.0.3 on 2026-06-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_remove_parkingslot_unique_slot_number_per_lot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingslot',
            name='controller_id',
        ),
        migrations.RemoveField(
            model_name='parkingslot',
            name='hardware_slot_id',
        ),
        migrations.RemoveField(
            model_name='parkingslot',
            name='is_hardware_slot',
        ),
        migrations.RemoveField(
            model_name='parkingslot',
            name='last_sensor_update',
        ),
        migrations.RemoveField(
            model_name='parkingslot',
            name='occupancy_status',
        ),
        migrations.RemoveField(
            model_name='parkingslot',
            name='sensor_id',
        ),
    ]
