# Generated by Django 6.0.3 on 2026-06-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_remove_hardware_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time_extended_by',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
