# Generated by Django 6.0.3 on 2026-07-12 18:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_seed_initial_parking_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
